// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Folder struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Note struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Content         string         `json:"content"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	EmbeddingSynced sql.NullBool   `json:"embedding_synced"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	Source          sql.NullString `json:"source"`
	SourceRef       sql.NullString `json:"source_ref"`
	FolderID        sql.NullInt64  `json:"folder_id"`
	Pinned          sql.NullBool   `json:"pinned"`
	PinnedAt        sql.NullTime   `json:"pinned_at"`
}

type NoteLink struct {
	ID           int64        `json:"id"`
	SourceNoteID int64        `json:"source_note_id"`
	TargetNoteID int64        `json:"target_note_id"`
	LinkText     string       `json:"link_text"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type NoteTag struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
