// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Note struct {
	ID              int64        `json:"id"`
	Title           string       `json:"title"`
	Content         string       `json:"content"`
	CreatedAt       sql.NullTime `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
	EmbeddingSynced sql.NullBool `json:"embedding_synced"`
}

type NoteTag struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
