// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const addTagToNote = `-- name: AddTagToNote :exec

INSERT INTO note_tags (note_id, tag_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddTagToNoteParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

// Note Tags --
func (q *Queries) AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error {
	_, err := q.db.ExecContext(ctx, addTagToNote, arg.NoteID, arg.TagID)
	return err
}

const countNotes = `-- name: CountNotes :one

SELECT COUNT(*) FROM notes
`

// Count queries (avoid loading all rows)
func (q *Queries) CountNotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTags = `-- name: CountTags :one
SELECT COUNT(*) FROM tags
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one

INSERT INTO folders (name, parent_id)
VALUES (?, ?)
RETURNING id, name, parent_id, created_at, updated_at
`

type CreateFolderParams struct {
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
}

// Folders --
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, arg.Name, arg.ParentID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (title, content)
VALUES (?, ?)
RETURNING id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at
`

type CreateNoteParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
		&i.ExpiresAt,
		&i.Source,
		&i.SourceRef,
		&i.FolderID,
		&i.Pinned,
		&i.PinnedAt,
	)
	return i, err
}

const createNoteLink = `-- name: CreateNoteLink :exec

INSERT INTO note_links (source_note_id, target_note_id, link_text)
VALUES (?, ?, ?)
ON CONFLICT DO NOTHING
`

type CreateNoteLinkParams struct {
	SourceNoteID int64  `json:"source_note_id"`
	TargetNoteID int64  `json:"target_note_id"`
	LinkText     string `json:"link_text"`
}

// Note links (wikilinks / bidirectional linking)
func (q *Queries) CreateNoteLink(ctx context.Context, arg CreateNoteLinkParams) error {
	_, err := q.db.ExecContext(ctx, createNoteLink, arg.SourceNoteID, arg.TargetNoteID, arg.LinkText)
	return err
}

const createNoteWithTTL = `-- name: CreateNoteWithTTL :one
INSERT INTO notes (title, content, expires_at, source, source_ref)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at
`

type CreateNoteWithTTLParams struct {
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
	Source    sql.NullString `json:"source"`
	SourceRef sql.NullString `json:"source_ref"`
}

func (q *Queries) CreateNoteWithTTL(ctx context.Context, arg CreateNoteWithTTLParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNoteWithTTL,
		arg.Title,
		arg.Content,
		arg.ExpiresAt,
		arg.Source,
		arg.SourceRef,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
		&i.ExpiresAt,
		&i.Source,
		&i.SourceRef,
		&i.FolderID,
		&i.Pinned,
		&i.PinnedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (name)
VALUES (?)
ON CONFLICT (name) DO UPDATE SET name = name
RETURNING id, name
`

// Tags --
func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteExpiredNotes = `-- name: DeleteExpiredNotes :execresult
DELETE FROM notes WHERE expires_at IS NOT NULL AND expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredNotes(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredNotes)
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = ?
`

func (q *Queries) DeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, id)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteNoteLinks = `-- name: DeleteNoteLinks :exec
DELETE FROM note_links WHERE source_note_id = ?
`

func (q *Queries) DeleteNoteLinks(ctx context.Context, sourceNoteID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNoteLinks, sourceNoteID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteUnusedTags = `-- name: DeleteUnusedTags :execrows
DELETE FROM tags
WHERE id NOT IN (SELECT DISTINCT tag_id FROM note_tags)
`

func (q *Queries) DeleteUnusedTags(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedTags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllNoteLinks = `-- name: GetAllNoteLinks :many
SELECT id, source_note_id, target_note_id, link_text, created_at FROM note_links
`

func (q *Queries) GetAllNoteLinks(ctx context.Context) ([]NoteLink, error) {
	rows, err := q.db.QueryContext(ctx, getAllNoteLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoteLink{}
	for rows.Next() {
		var i NoteLink
		if err := rows.Scan(
			&i.ID,
			&i.SourceNoteID,
			&i.TargetNoteID,
			&i.LinkText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllNotes = `-- name: GetAllNotes :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes ORDER BY created_at DESC
`

func (q *Queries) GetAllNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBacklinks = `-- name: GetBacklinks :many
SELECT n.id, n.title, n.content, n.created_at, n.updated_at, n.embedding_synced, n.expires_at, n.source, n.source_ref, n.folder_id, n.pinned, n.pinned_at FROM notes n
INNER JOIN note_links nl ON n.id = nl.source_note_id
WHERE nl.target_note_id = ?
ORDER BY n.updated_at DESC
`

func (q *Queries) GetBacklinks(ctx context.Context, targetNoteID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getBacklinks, targetNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredNotes = `-- name: GetExpiredNotes :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes WHERE expires_at IS NOT NULL AND expires_at < datetime('now')
`

func (q *Queries) GetExpiredNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolder = `-- name: GetFolder :one
SELECT id, name, parent_id, created_at, updated_at FROM folders WHERE id = ?
`

func (q *Queries) GetFolder(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes
WHERE id = ?
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
		&i.ExpiresAt,
		&i.Source,
		&i.SourceRef,
		&i.FolderID,
		&i.Pinned,
		&i.PinnedAt,
	)
	return i, err
}

const getNoteByTitle = `-- name: GetNoteByTitle :one
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes WHERE title = ? LIMIT 1
`

func (q *Queries) GetNoteByTitle(ctx context.Context, title string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByTitle, title)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
		&i.ExpiresAt,
		&i.Source,
		&i.SourceRef,
		&i.FolderID,
		&i.Pinned,
		&i.PinnedAt,
	)
	return i, err
}

const getNotesByFolder = `-- name: GetNotesByFolder :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes
WHERE folder_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetNotesByFolder(ctx context.Context, folderID sql.NullInt64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesByTagName = `-- name: GetNotesByTagName :many
SELECT n.id, n.title, n.content, n.created_at, n.updated_at, n.embedding_synced, n.expires_at, n.source, n.source_ref, n.folder_id, n.pinned, n.pinned_at FROM notes n
INNER JOIN note_tags nt ON n.id = nt.note_id
INNER JOIN tags t ON nt.tag_id = t.id
WHERE t.name = ?
ORDER BY n.created_at DESC
`

func (q *Queries) GetNotesByTagName(ctx context.Context, name string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByTagName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesForTag = `-- name: GetNotesForTag :many
SELECT n.id, n.title, n.content, n.created_at, n.updated_at, n.embedding_synced, n.expires_at, n.source, n.source_ref, n.folder_id, n.pinned, n.pinned_at FROM notes n
INNER JOIN note_tags nt ON n.id = nt.note_id
WHERE nt.tag_id = ?
ORDER BY n.created_at DESC
`

func (q *Queries) GetNotesForTag(ctx context.Context, tagID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesForTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesSince = `-- name: GetNotesSince :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes WHERE created_at >= ? ORDER BY created_at DESC
`

func (q *Queries) GetNotesSince(ctx context.Context, createdAt sql.NullTime) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesWithoutFolder = `-- name: GetNotesWithoutFolder :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes
WHERE folder_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetNotesWithoutFolder(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesWithoutFolder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutlinks = `-- name: GetOutlinks :many
SELECT n.id, n.title, n.content, n.created_at, n.updated_at, n.embedding_synced, n.expires_at, n.source, n.source_ref, n.folder_id, n.pinned, n.pinned_at FROM notes n
INNER JOIN note_links nl ON n.id = nl.target_note_id
WHERE nl.source_note_id = ?
ORDER BY n.title
`

func (q *Queries) GetOutlinks(ctx context.Context, sourceNoteID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getOutlinks, sourceNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPinnedNotes = `-- name: GetPinnedNotes :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes WHERE pinned = TRUE ORDER BY pinned_at DESC
`

func (q *Queries) GetPinnedNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getPinnedNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags
WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagsForNote = `-- name: GetTagsForNote :many
SELECT t.id, t.name FROM tags t
INNER JOIN note_tags nt ON t.id = nt.tag_id
WHERE nt.note_id = ?
ORDER BY t.name
`

func (q *Queries) GetTagsForNote(ctx context.Context, noteID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsWithCount = `-- name: GetTagsWithCount :many
SELECT t.id, t.name, COUNT(nt.note_id) as note_count
FROM tags t
LEFT JOIN note_tags nt ON t.id = nt.tag_id
GROUP BY t.id
ORDER BY t.name
`

type GetTagsWithCountRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	NoteCount int64  `json:"note_count"`
}

func (q *Queries) GetTagsWithCount(ctx context.Context) ([]GetTagsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsWithCountRow{}
	for rows.Next() {
		var i GetTagsWithCountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.NoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsynced = `-- name: GetUnsynced :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes
WHERE embedding_synced = FALSE
`

func (q *Queries) GetUnsynced(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getUnsynced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, name, parent_id, created_at, updated_at FROM folders ORDER BY name
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNotesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmbeddingSynced = `-- name: MarkEmbeddingSynced :exec
UPDATE notes
SET embedding_synced = TRUE
WHERE id = ?
`

func (q *Queries) MarkEmbeddingSynced(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmbeddingSynced, id)
	return err
}

const moveNoteToFolder = `-- name: MoveNoteToFolder :exec
UPDATE notes
SET folder_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MoveNoteToFolderParams struct {
	FolderID sql.NullInt64 `json:"folder_id"`
	ID       int64         `json:"id"`
}

func (q *Queries) MoveNoteToFolder(ctx context.Context, arg MoveNoteToFolderParams) error {
	_, err := q.db.ExecContext(ctx, moveNoteToFolder, arg.FolderID, arg.ID)
	return err
}

const pinNote = `-- name: PinNote :exec

UPDATE notes SET pinned = TRUE, pinned_at = CURRENT_TIMESTAMP WHERE id = ?
`

// Pin/star support
func (q *Queries) PinNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, pinNote, id)
	return err
}

const removeAllTagsFromNote = `-- name: RemoveAllTagsFromNote :exec
DELETE FROM note_tags WHERE note_id = ?
`

func (q *Queries) RemoveAllTagsFromNote(ctx context.Context, noteID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromNote, noteID)
	return err
}

const removeTagFromNote = `-- name: RemoveTagFromNote :exec
DELETE FROM note_tags
WHERE note_id = ? AND tag_id = ?
`

type RemoveTagFromNoteParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromNote(ctx context.Context, arg RemoveTagFromNoteParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromNote, arg.NoteID, arg.TagID)
	return err
}

const searchNotesByTitle = `-- name: SearchNotesByTitle :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes
WHERE title LIKE ?
ORDER BY created_at DESC
`

func (q *Queries) SearchNotesByTitle(ctx context.Context, title string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesByTitle, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesContent = `-- name: SearchNotesContent :many
SELECT id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at FROM notes
WHERE content LIKE ? OR title LIKE ?
ORDER BY updated_at DESC
LIMIT ?
`

type SearchNotesContentParams struct {
	Content string `json:"content"`
	Title   string `json:"title"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) SearchNotesContent(ctx context.Context, arg SearchNotesContentParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesContent, arg.Content, arg.Title, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
			&i.ExpiresAt,
			&i.Source,
			&i.SourceRef,
			&i.FolderID,
			&i.Pinned,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unpinNote = `-- name: UnpinNote :exec
UPDATE notes SET pinned = FALSE, pinned_at = NULL WHERE id = ?
`

func (q *Queries) UnpinNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unpinNote, id)
	return err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET name = ?, parent_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, parent_id, created_at, updated_at
`

type UpdateFolderParams struct {
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, updateFolder, arg.Name, arg.ParentID, arg.ID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = ?, content = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, content, created_at, updated_at, embedding_synced, expires_at, source, source_ref, folder_id, pinned, pinned_at
`

type UpdateNoteParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.Title, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
		&i.ExpiresAt,
		&i.Source,
		&i.SourceRef,
		&i.FolderID,
		&i.Pinned,
		&i.PinnedAt,
	)
	return i, err
}

const updateNoteSource = `-- name: UpdateNoteSource :exec
UPDATE notes SET source = ?, source_ref = ? WHERE id = ?
`

type UpdateNoteSourceParams struct {
	Source    sql.NullString `json:"source"`
	SourceRef sql.NullString `json:"source_ref"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateNoteSource(ctx context.Context, arg UpdateNoteSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateNoteSource, arg.Source, arg.SourceRef, arg.ID)
	return err
}
