// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const addTagToNote = `-- name: AddTagToNote :exec

INSERT INTO note_tags (note_id, tag_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddTagToNoteParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

// Note Tags --
func (q *Queries) AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error {
	_, err := q.db.ExecContext(ctx, addTagToNote, arg.NoteID, arg.TagID)
	return err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (title, content)
VALUES (?, ?)
RETURNING id, title, content, created_at, updated_at, embedding_synced
`

type CreateNoteParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (name)
VALUES (?)
ON CONFLICT (name) DO UPDATE SET name = name
RETURNING id, name
`

// Tags --
func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteUnusedTags = `-- name: DeleteUnusedTags :execrows
DELETE FROM tags
WHERE id NOT IN (SELECT DISTINCT tag_id FROM note_tags)
`

func (q *Queries) DeleteUnusedTags(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedTags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllNotes = `-- name: GetAllNotes :many
SELECT id, title, content, created_at, updated_at, embedding_synced FROM notes ORDER BY created_at DESC
`

func (q *Queries) GetAllNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNote = `-- name: GetNote :one
SELECT id, title, content, created_at, updated_at, embedding_synced FROM notes
WHERE id = ?
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
	)
	return i, err
}

const getNotesByTagName = `-- name: GetNotesByTagName :many
SELECT n.id, n.title, n.content, n.created_at, n.updated_at, n.embedding_synced FROM notes n
INNER JOIN note_tags nt ON n.id = nt.note_id
INNER JOIN tags t ON nt.tag_id = t.id
WHERE t.name = ?
ORDER BY n.created_at DESC
`

func (q *Queries) GetNotesByTagName(ctx context.Context, name string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByTagName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesForTag = `-- name: GetNotesForTag :many
SELECT n.id, n.title, n.content, n.created_at, n.updated_at, n.embedding_synced FROM notes n
INNER JOIN note_tags nt ON n.id = nt.note_id
WHERE nt.tag_id = ?
ORDER BY n.created_at DESC
`

func (q *Queries) GetNotesForTag(ctx context.Context, tagID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesForTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags
WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagsForNote = `-- name: GetTagsForNote :many
SELECT t.id, t.name FROM tags t
INNER JOIN note_tags nt ON t.id = nt.tag_id
WHERE nt.note_id = ?
ORDER BY t.name
`

func (q *Queries) GetTagsForNote(ctx context.Context, noteID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsWithCount = `-- name: GetTagsWithCount :many
SELECT t.id, t.name, COUNT(nt.note_id) as note_count
FROM tags t
LEFT JOIN note_tags nt ON t.id = nt.tag_id
GROUP BY t.id
ORDER BY t.name
`

type GetTagsWithCountRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	NoteCount int64  `json:"note_count"`
}

func (q *Queries) GetTagsWithCount(ctx context.Context) ([]GetTagsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsWithCountRow{}
	for rows.Next() {
		var i GetTagsWithCountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.NoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsynced = `-- name: GetUnsynced :many
SELECT id, title, content, created_at, updated_at, embedding_synced FROM notes
WHERE embedding_synced = FALSE
`

func (q *Queries) GetUnsynced(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getUnsynced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, content, created_at, updated_at, embedding_synced FROM notes
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNotesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmbeddingSynced = `-- name: MarkEmbeddingSynced :exec
UPDATE notes
SET embedding_synced = TRUE
WHERE id = ?
`

func (q *Queries) MarkEmbeddingSynced(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmbeddingSynced, id)
	return err
}

const removeAllTagsFromNote = `-- name: RemoveAllTagsFromNote :exec
DELETE FROM note_tags WHERE note_id = ?
`

func (q *Queries) RemoveAllTagsFromNote(ctx context.Context, noteID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromNote, noteID)
	return err
}

const removeTagFromNote = `-- name: RemoveTagFromNote :exec
DELETE FROM note_tags
WHERE note_id = ? AND tag_id = ?
`

type RemoveTagFromNoteParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromNote(ctx context.Context, arg RemoveTagFromNoteParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromNote, arg.NoteID, arg.TagID)
	return err
}

const searchNotesByTitle = `-- name: SearchNotesByTitle :many
SELECT id, title, content, created_at, updated_at, embedding_synced FROM notes
WHERE title LIKE ?
ORDER BY created_at DESC
`

func (q *Queries) SearchNotesByTitle(ctx context.Context, title string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesByTitle, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesContent = `-- name: SearchNotesContent :many
SELECT id, title, content, created_at, updated_at, embedding_synced FROM notes
WHERE content LIKE ? OR title LIKE ?
ORDER BY updated_at DESC
LIMIT ?
`

type SearchNotesContentParams struct {
	Content string `json:"content"`
	Title   string `json:"title"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) SearchNotesContent(ctx context.Context, arg SearchNotesContentParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesContent, arg.Content, arg.Title, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmbeddingSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = ?, content = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, content, created_at, updated_at, embedding_synced
`

type UpdateNoteParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.Title, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmbeddingSynced,
	)
	return i, err
}
